include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - public_member_api_docs
    - sort_child_properties_last
    - unnecessary_lambdas
    - use_super_parameters
