name: preview_hub
description: "A runnable gallery for previewing a design system's widgets, icons, images, animations and font families on a real device."
version: 0.0.1
repository: https://github.com/anupam92402/PreviewHub

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
